// <auto-generated />
using System;
using Home_Service_Finder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Home_Service_Finder.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250416180540_updated location tabsss")]
    partial class updatedlocationtabsss
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Home_Service_Finder.Authentication.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("ExpriesOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken", "Users");
                });

            modelBuilder.Entity("Home_Service_Finder.Email.EmailOTP", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("VARCHAR(6)")
                        .HasColumnName("Code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("ExpiryTime");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("IsUsed");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmailOTP", "Users");
                });

            modelBuilder.Entity("Home_Service_Finder.Locations.Location", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("Address");

                    b.Property<string>("City")
                        .HasColumnType("varchar")
                        .HasColumnName("City");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("Latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("Longitude");

                    b.Property<string>("PostalCode")
                        .HasColumnType("varchar")
                        .HasColumnName("PostalCode");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("UserId");

                    b.ToTable("Location", "Locations");
                });

            modelBuilder.Entity("Home_Service_Finder.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Role", "Users");
                });

            modelBuilder.Entity("Home_Service_Finder.ServiceCategories.ServiceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("CategoryImage")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("CategoryImage");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("ModifiedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("ServieCategory", "Services");
                });

            modelBuilder.Entity("Home_Service_Finder.ServicesList.ServiceList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("ModifiedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(250)")
                        .HasColumnName("Name");

                    b.Property<Guid>("ServiceCategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceCategoryId");

                    b.ToTable("ServiceList", "Services");
                });

            modelBuilder.Entity("Home_Service_Finder.Users.ServiceProvider.ServiceProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<int>("Experience")
                        .HasColumnType("INT")
                        .HasColumnName("Experience");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsAdminVerified")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("IsAdminVerified");

                    b.Property<string>("PersonalDescription")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("PersonalDescription");

                    b.Property<Guid>("ServiceCategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceCategoryId");

                    b.ToTable("ServiceProvider", "Users");
                });

            modelBuilder.Entity("Home_Service_Finder.Users.UserDetails.UserDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("DATE")
                        .HasColumnName("DateOfBirth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("FirstName");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("LastName");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("ProfilePicture");

                    b.HasKey("Id");

                    b.ToTable("UserDetail", "Users");
                });

            modelBuilder.Entity("Home_Service_Finder.Users.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("Email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("IsEmailVerified");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("ModifiedAt");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("Password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("PhoneNumber");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("User", "Users");
                });

            modelBuilder.Entity("Home_Service_Finder.Authentication.RefreshToken", b =>
                {
                    b.HasOne("Home_Service_Finder.Users.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Home_Service_Finder.Email.EmailOTP", b =>
                {
                    b.HasOne("Home_Service_Finder.Users.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Home_Service_Finder.Locations.Location", b =>
                {
                    b.HasOne("Home_Service_Finder.Users.Users.User", "User")
                        .WithOne("Location")
                        .HasForeignKey("Home_Service_Finder.Locations.Location", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Home_Service_Finder.ServicesList.ServiceList", b =>
                {
                    b.HasOne("Home_Service_Finder.ServiceCategories.ServiceCategory", "ServiceCategory")
                        .WithMany("Services")
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("Home_Service_Finder.Users.ServiceProvider.ServiceProvider", b =>
                {
                    b.HasOne("Home_Service_Finder.Users.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Home_Service_Finder.ServiceCategories.ServiceCategory", "ServiceCategory")
                        .WithMany()
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Home_Service_Finder.Users.UserDetails.UserDetail", b =>
                {
                    b.HasOne("Home_Service_Finder.Users.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Home_Service_Finder.Users.Users.User", b =>
                {
                    b.HasOne("Home_Service_Finder.Roles.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Home_Service_Finder.ServiceCategories.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("Home_Service_Finder.Users.Users.User", b =>
                {
                    b.Navigation("Location")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
